version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URI=http://10.10.10.30:8083
